name: Execute e Exporte Calculo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute_export_calculo:
    name: Execute e Exporte Calculo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Usar a versão 3.11 do Python

    - name: Run calculation script and save result to resultado.txt
      run: |
        python calculo.py > $GITHUB_WORKSPACE/resultado.txt

    - name: Display result
      run: cat $GITHUB_WORKSPACE/resultado.txt

    - name: Configure Git user and email
      run: |
        git config --global user.email "elias.andrade@konecty.com"
        git config --global user.name "GitHub Actions"

    - name: Add resultado.txt to Git
      run: |
        git add $GITHUB_WORKSPACE/resultado.txt
        git commit -m "Add resultado.txt"

    - name: Push changes
      uses: actions/checkout@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
