name: Install Python 3.11

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_python:
    name: Install Python 3.11
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Verify Python installation
      run: python --version
